require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance
  - rubocop-minitest
  - rubocop-graphql

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - Gemfile
    - 'vendor/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 25

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false
